dist: bionic
language: go
services:
  - docker
go:
  - 1.19.x
env:
  global:
    - CGO_ENABLED=1
    - GO111MODULE=on
gobuild_args: -a -tags netgo -ldflags "-w -X main.version=${TRAVIS_COMMIT}"
go_import_path: github.com/adevinta/vulcan-agent
script:
  - go test -short -race -v $(go list ./... | grep -v /vendor/)
